baseURL = "https://portblog.xyz"
baseurl = "/"
disqusShortname = "PortBlog"
languageCode = "en-us"
paginate = 6
theme = "terminal"
title = "PortBlog"
[languages.en]
copyright = ""
keywords = ""
languageName = "Portuguese"
menuMore = "Veja Mais"
owner = ""
readMore = "Leia mais"
readOtherPosts = "Outras Publicações"
subtitle = "Simples e descomplicado"
title = "PortBlog"
[[languages.en.menu.main]]
identifier = "about"
name = "SOBRE NÓS"
url = "/about"
[[languages.en.menu.main]]
identifier = "techStack"
name = "TECH STACK"
url = "/techStack"
[[languages.en.menu.main]]
identifier = "projetosPessoais"
name = "PROJETOS PESSOAIS"
url = "/projetosPessoais"
[[languages.en.menu.main]]
identifier = "linkGit"
name = "GIT-HUB"
url = "https://github.com/prosperor/PI2Blog"
[languages.en.params.logo]
logoHomeLink = "/"
logoText = "PORTBLOG"
[params]
centerTheme = true
contentTypeName = "post"
fullWidthTheme = false
showLanguageSelector = false
showMenuItems = 4
themeColor = "red"
[params.twitter]
creator = "Fabio e Próspero"
site = ""
